name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]

permissions:
  contents: write
jobs:
  convert-to-managed:
    runs-on: windows-latest
    environment: development
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: solutions/PowerAppsDeployment
        solution-file: out/solutions/PowerAppsDeployment.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to build env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{secrets.BUILD_ENVIRONMENT_URL}}
        user-name: ${{ secrets.USERNAME }}
        password-secret: ${{ secrets.PASSWORD }}
        solution-file: out/solutions/PowerAppsDeployment.zip
        force-overwrite: true
        publish-changes: true

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{secrets.BUILD_ENVIRONMENT_URL}}
        user-name: ${{ secrets.USERNAME }}
        password-secret: ${{ secrets.PASSWORD }}
        solution-name: PowerAppsDeployment
        managed: true
        solution-output-file: out/ship/PowerAppsDeployment.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: out/ship/

  release-to-production:
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    environment: development
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: out/release
    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{secrets.PRODUCTION_ENVIRONMENT_URL}}
        user-name: ${{ secrets.USERNAME }}
        password-secret: ${{ secrets.PASSWORD }}
        solution-file: out/release/PowerAppsDeployment.zip
        force-overwrite: true
        publish-changes: true

